=== gehuang/cdttable-matlab/+nevreader/nev_rewarded_trial_template_schema.json
{
  "$schema":"http://json-schema.org/draft-04/schema#",
  "type":"object",
  "properties":{
    "codes":{
      "type":"array",
      "items":{
        "oneOf":[
          {
            "oneOf":[
              {
                "type":"object",
                "properties":{
                  "type":{
                    "type":"string",
                    "enum":[
                      "SINGLE"
                    ]
                  },
                  "code":{
                    "type":"integer"
                  },
                  "missable":{
                    "type":"boolean",
                    "enum":[
                      false
                    ]
                  }
                },
                "required":[
                  "type",
                  "code",
                  "missable"
                ],
                "additionalProperties":false
              },
              {
                "type":"object",
                "properties":{
                  "type":{
                    "type":"string",
                    "enum":[
                      "SINGLE"
                    ]
                  },
                  "code":{
                    "type":"integer"
                  }
                },
                "required":[
                  "type",
                  "code"
                ],
                "additionalProperties":false
              }
            ]
          },
          {
            "type":"object",
            "properties":{
              "type":{
                "type":"string",
                "enum":[
                  "RANGE"
                ]
              },
              "min_value":{
                "type":"integer"
              },
              "max_value":{
                "type":"integer"
              },
              "missable":{
                "type":"boolean"
              }
            },
            "required":[
              "type",
              "min_value",
              "max_value",
              "missable"
            ],
            "additionalProperties":false
          }
        ]
      },
      "minItems":1
    },
    "comment":{
      "type":"string"
    },
    "startcode":{
      "type":"integer"
    },
    "stopcode":{
      "type":"integer"
    },
    "rewardcode":{
      "type":"integer"
    }
  },
  "required":[
    "codes",
    "startcode",
    "stopcode",
    "rewardcode"
  ],
  "additionalProperties":false
}

=== gehuang/cdttable-matlab/+nevreader/demo_trial_templates/3ec_images.json
{
  "comment":"trial template for 3ec_xxx tm file and images cnd file",
  "startcode":9,
  "stopcode":18,
  "rewardcode":96,
  "codes":[
    {
      "code":9,
      "type":"SINGLE"
    },
    {
      "code":10,
      "type":"SINGLE"
    },
    {
      "code":15,
      "type":"SINGLE"
    },
    {
      "code":100,
      "type":"SINGLE"
    },
    {
      "code":16,
      "type":"SINGLE"
    },
    {
      "missable":false,
      "max_value":192,
      "min_value":192,
      "type":"RANGE"
    },
    {
      "missable":true,
      "max_value":208,
      "min_value":192,
      "type":"RANGE"
    },
    {
      "code":23,
      "type":"SINGLE"
    },
    {
      "code":8,
      "type":"SINGLE"
    },
    {
      "code":25,
      "type":"SINGLE"
    },
    {
      "code":26,
      "type":"SINGLE"
    },
    {
      "code":27,
      "type":"SINGLE"
    },
    {
      "code":28,
      "type":"SINGLE"
    },
    {
      "code":29,
      "type":"SINGLE"
    },
    {
      "code":30,
      "type":"SINGLE"
    },
    {
      "missable":false,
      "max_value":124,
      "min_value":121,
      "type":"RANGE"
    },
    {
      "code":120,
      "type":"SINGLE"
    },
    {
      "code":8,
      "type":"SINGLE"
    },
    {
      "code":24,
      "type":"SINGLE"
    },
    {
      "code":17,
      "type":"SINGLE"
    },
    {
      "code":0,
      "type":"SINGLE"
    },
    {
      "code":101,
      "type":"SINGLE"
    },
    {
      "code":96,
      "type":"SINGLE"
    },
    {
      "code":18,
      "type":"SINGLE"
    }
  ]
}

=== gehuang/cdttable-matlab/+nevreader/demo_trial_templates/cg.json
{
  "comment":"trial template for contrast tm file and contrast cnd file",
  "startcode":9,
  "stopcode":18,
  "rewardcode":96,
  "codes":[
    {
      "code":9,
      "type":"SINGLE"
    },
    {
      "code":10,
      "type":"SINGLE"
    },
    {
      "code":15,
      "type":"SINGLE"
    },
    {
      "missable":false,
      "max_value":171,
      "min_value":140,
      "type":"RANGE"
    },
    {
      "code":100,
      "type":"SINGLE"
    },
    {
      "code":16,
      "type":"SINGLE"
    },
    {
      "code":23,
      "type":"SINGLE"
    },
    {
      "code":8,
      "type":"SINGLE"
    },
    {
      "code":33,
      "type":"SINGLE"
    },
    {
      "code":31,
      "type":"SINGLE"
    },
    {
      "missable":false,
      "max_value":123,
      "min_value":121,
      "type":"RANGE"
    },
    {
      "code":120,
      "type":"SINGLE"
    },
    {
      "code":11,
      "type":"SINGLE"
    },
    {
      "code":8,
      "type":"SINGLE"
    },
    {
      "code":31,
      "type":"SINGLE"
    },
    {
      "code":24,
      "type":"SINGLE"
    },
    {
      "code":17,
      "type":"SINGLE"
    },
    {
      "code":101,
      "type":"SINGLE"
    },
    {
      "code":96,
      "type":"SINGLE"
    },
    {
      "code":18,
      "type":"SINGLE"
    }
  ]
}
